#ifndef __DEFAULTVALUES_H__
#define __DEFAULTVALUES_H__

#define DEFAULT_CONFIGFILE "app.ini"

#define DEFAULT_NAME "Hello World!"
#define DEFAULT_VERSION "v0.1"
#define DEFAULT_WIDTH 800
#define DEFAULT_HEIGHT 600
#define DEFAULT_RAW_RESOURCES_PATH "res"
#define DEFAULT_RAW_RESOURCES_FILE_EXTENTION "*.raw"
#define DEFAULT_IMG_PATH "img"

#endif /* __DEFAULTVALUES_H__ */
